import type { Metadata } from "next";
import { Manrope, Raleway } from "next/font/google";
import "../styles/globals.css";
import { AppProviders } from "../components/providers/AppProviders";
import PrimaryHeader from "../components/layouts/header/PrimaryHeader";
import PrimaryFooter from "../components/layouts/footer/PrimaryFooter";
import { Toaster } from "react-hot-toast";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Aadrila - Identity Verification Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${raleway.variable} antialiased`}>
        <AppProviders>
          <Toaster />
          <main className="main_layout">
            <PrimaryHeader />
            {children}
            <PrimaryFooter />
          </main>
        </AppProviders>
      </body>
    </html>
  );
}
